export const bachelorTilKategori: any = {
  'Bachelor i økonomi og administrasjon': 'Økonomi',
  'Bachelor i regnskap og revisjon': 'Økonomi',
  'Bachelor i markedsføring og ledelse': 'Økonomi',
  'Bachelor i internasjonal business': 'Økonomi',
  'Bachelor i finans': 'Økonomi',
  'Bachelor i rettsvitenskap / jus': 'Lov og orden',
  'Bachelor i psykologi': 'Helse',
  'Bachelor i sosiologi': 'Samfunn',
  'Bachelor i statsvitenskap': 'Samfunn',
  'Bachelor i samfunnsøkonomi': 'Økonomi',
  'Bachelor i filosofi': 'Samfunn',
  'Bachelor i pedagogikk': 'Pedagogikk',
  'Bachelor i informatikk': 'IT og data',
  'Bachelor i datateknologi': 'IT og data',
  'Bachelor i kunstig intelligens': 'IT og data',
  'Bachelor i cybersikkerhet': 'IT og data',
  'Bachelor i ingeniør – data': 'Teknologi',
  'Bachelor i ingeniør – maskin': 'Teknologi',
  'Bachelor i ingeniør – bygg': 'Bygg og anlegg',
  'Bachelor i ingeniør – elektronikk': 'Elektronikk',
  'Bachelor i ingeniør – energi': 'Olje, gass og energi',
  'Bachelor i matematikk': 'Realfag',
  'Bachelor i fysikk': 'Realfag',
  'Bachelor i kjemi': 'Realfag',
  'Bachelor i biologi': 'Natur',
  'Bachelor i bioteknologi': 'Realfag',
  'Bachelor i sykepleie': 'Helse',
  'Bachelor i ergoterapi': 'Helse',
  'Bachelor i fysioterapi': 'Helse',
  'Bachelor i bioingeniør': 'Helse',
  'Bachelor i radiografi': 'Helse',
  'Bachelor i paramedisin': 'Helse',
  'Bachelor i farmasi': 'Helse',
  'Bachelor i tannpleie': 'Helse',
  'Bachelor i folkehelse': 'Helse',
  'Bachelor i barnevern': 'Barn',
  'Bachelor i sosialt arbeid': 'Mennesker',
  'Bachelor i vernepleie': 'Helse',
  'Bachelor i journalistikk': 'Media og kommunikasjon',
  'Bachelor i medievitenskap': 'Media og kommunikasjon',
  'Bachelor i kommunikasjon': 'Media og kommunikasjon',
  'Bachelor i film og TV-produksjon': 'Media og kommunikasjon',
  'Bachelor i kunst og design': 'Design',
  'Bachelor i arkitektur': 'Bygg og anlegg',
  'Bachelor i musikkvitenskap': 'Kunst og kultur',
  'Bachelor i idrettsvitenskap': 'Idrett',
  'Bachelor i friluftsliv': 'Idrett',
  'Bachelor i lærerutdanning 1–7': 'Pedagogikk',
  'Bachelor i lærerutdanning 5–10': 'Pedagogikk',
  'Bachelor i historie': 'Historie',
  'Bachelor i geografi': 'Natur',
  'Bachelor i nordisk språk og litteratur': 'Språk',
  'Bachelor i engelsk': 'Språk',
  'Bachelor i fransk': 'Språk',
  'Bachelor i tysk': 'Språk',
  'Bachelor i spansk': 'Språk',
  'Bachelor i arabisk': 'Språk',
  'Bachelor i kinesisk': 'Språk',
  'Bachelor i russisk': 'Språk',
  'Bachelor i landbruk': 'Landbruk',
  'Bachelor i havbruk': 'Fiskeri og havbruk',
  'Bachelor i veterinærmedisin': 'Dyr',
  'Bachelor i miljøvitenskap': 'Klima og miljø',
  'Bachelor i geologi': 'Realfag',
  'Bachelor i nanoteknologi': 'Teknologi',
}